name: Name-On CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  checkout_job:
    uses: ./.github/workflows/checkout.yml
  setup_dotnet_job:
    needs: checkout_job
    uses: ./.github/workflows/setup-dotnet.yml
  publish_blazor_job:
    needs: setup_dotnet_job
    uses: ./.github/workflows/publish-blazor.yml
  deploy_job:
    needs: publish_blazor_job
    uses: ./.github/workflows/deploy.yml
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/close-pull-request.yml
