name: Publish Blazor WASM

on: [workflow_call]

jobs:
  publish_blazor_job:
    runs-on: ubuntu-latest
    name: Publish Blazor WASM
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Publish Blazor WASM
        run: dotnet publish ./name-on-blazor/name-on-blazor.csproj -c Release -o build_output
